/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Alert {
  'id' : bigint,
  'user' : Principal,
  'acknowledged' : boolean,
  'message' : string,
}
export interface Dashboard {
  'id' : bigint,
  'widgets' : Array<Widget>,
  'owner' : Principal,
  'name' : string,
}
export interface Integration {
  'id' : IntegrationType,
  'apiKey' : [] | [string],
  'connected' : boolean,
}
export type IntegrationType = { 'loxo' : null } |
  { 'timesheets' : null } |
  { 'aircall' : null };
export interface Organization {
  'principal' : Principal,
  'integrations' : Array<Integration>,
  'orgType' : OrganizationType,
  'name' : string,
}
export type OrganizationType = { 'internalTA' : null } |
  { 'staffing' : null };
export interface SystemUserRecord {
  'name' : string,
  'integrationId' : string,
  'email' : string,
  'integrationType' : IntegrationType,
  'organization' : Principal,
}
export type Time = bigint;
export interface TimesheetRecord {
  'hours' : number,
  'userId' : string,
  'date' : Time,
  'billable' : boolean,
  'organization' : Principal,
}
export interface UserMapping {
  'timesheetUserId' : [] | [string],
  'canisterUser' : Principal,
  'aircallUserId' : [] | [string],
  'loxoUserId' : [] | [string],
}
export interface UserProfile {
  'organizationId' : [] | [Principal],
  'name' : string,
  'email' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Widget {
  'id' : bigint,
  'widgetType' : WidgetType,
  'config' : string,
}
export type WidgetType = { 'table' : null } |
  { 'trendChart' : null } |
  { 'kpiCard' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acknowledgeAlert' : ActorMethod<[Principal], undefined>,
  'addAlert' : ActorMethod<[Alert], undefined>,
  'addOrganization' : ActorMethod<[string, OrganizationType], undefined>,
  'addSystemUserRecord' : ActorMethod<[SystemUserRecord], undefined>,
  'addTimesheetRecord' : ActorMethod<[TimesheetRecord], undefined>,
  'addUserMapping' : ActorMethod<[UserMapping], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createDashboard' : ActorMethod<[string, Array<Widget>], bigint>,
  'getAlert' : ActorMethod<[Principal], Alert>,
  'getAllAlerts' : ActorMethod<[], Array<Alert>>,
  'getAllDashboards' : ActorMethod<[], Array<Dashboard>>,
  'getAllOrganizations' : ActorMethod<[], Array<Organization>>,
  'getAllTimesheetRecords' : ActorMethod<[], Array<TimesheetRecord>>,
  'getAllUserMappings' : ActorMethod<[], Array<UserMapping>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboard' : ActorMethod<[bigint], Dashboard>,
  'getOrganization' : ActorMethod<[Principal], Organization>,
  'getSystemUserRecordsByIntegration' : ActorMethod<
    [string],
    Array<SystemUserRecord>
  >,
  'getTimesheetRecord' : ActorMethod<[Principal], TimesheetRecord>,
  'getUserMapping' : ActorMethod<[Principal], UserMapping>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateDashboard' : ActorMethod<[bigint, string, Array<Widget>], undefined>,
  'updateIntegration' : ActorMethod<[Principal, Integration], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];