/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Alert = IDL.Record({
  'id' : IDL.Nat,
  'user' : IDL.Principal,
  'acknowledged' : IDL.Bool,
  'message' : IDL.Text,
});
export const OrganizationType = IDL.Variant({
  'internalTA' : IDL.Null,
  'staffing' : IDL.Null,
});
export const IntegrationType = IDL.Variant({
  'loxo' : IDL.Null,
  'timesheets' : IDL.Null,
  'aircall' : IDL.Null,
});
export const SystemUserRecord = IDL.Record({
  'name' : IDL.Text,
  'integrationId' : IDL.Text,
  'email' : IDL.Text,
  'integrationType' : IntegrationType,
  'organization' : IDL.Principal,
});
export const Time = IDL.Int;
export const TimesheetRecord = IDL.Record({
  'hours' : IDL.Float64,
  'userId' : IDL.Text,
  'date' : Time,
  'billable' : IDL.Bool,
  'organization' : IDL.Principal,
});
export const UserMapping = IDL.Record({
  'timesheetUserId' : IDL.Opt(IDL.Text),
  'canisterUser' : IDL.Principal,
  'aircallUserId' : IDL.Opt(IDL.Text),
  'loxoUserId' : IDL.Opt(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const WidgetType = IDL.Variant({
  'table' : IDL.Null,
  'trendChart' : IDL.Null,
  'kpiCard' : IDL.Null,
});
export const Widget = IDL.Record({
  'id' : IDL.Nat,
  'widgetType' : WidgetType,
  'config' : IDL.Text,
});
export const Dashboard = IDL.Record({
  'id' : IDL.Nat,
  'widgets' : IDL.Vec(Widget),
  'owner' : IDL.Principal,
  'name' : IDL.Text,
});
export const Integration = IDL.Record({
  'id' : IntegrationType,
  'apiKey' : IDL.Opt(IDL.Text),
  'connected' : IDL.Bool,
});
export const Organization = IDL.Record({
  'principal' : IDL.Principal,
  'integrations' : IDL.Vec(Integration),
  'orgType' : OrganizationType,
  'name' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'organizationId' : IDL.Opt(IDL.Principal),
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acknowledgeAlert' : IDL.Func([IDL.Principal], [], []),
  'addAlert' : IDL.Func([Alert], [], []),
  'addOrganization' : IDL.Func([IDL.Text, OrganizationType], [], []),
  'addSystemUserRecord' : IDL.Func([SystemUserRecord], [], []),
  'addTimesheetRecord' : IDL.Func([TimesheetRecord], [], []),
  'addUserMapping' : IDL.Func([UserMapping], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createDashboard' : IDL.Func([IDL.Text, IDL.Vec(Widget)], [IDL.Nat], []),
  'getAlert' : IDL.Func([IDL.Principal], [Alert], ['query']),
  'getAllAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
  'getAllDashboards' : IDL.Func([], [IDL.Vec(Dashboard)], ['query']),
  'getAllOrganizations' : IDL.Func([], [IDL.Vec(Organization)], ['query']),
  'getAllTimesheetRecords' : IDL.Func(
      [],
      [IDL.Vec(TimesheetRecord)],
      ['query'],
    ),
  'getAllUserMappings' : IDL.Func([], [IDL.Vec(UserMapping)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboard' : IDL.Func([IDL.Nat], [Dashboard], ['query']),
  'getOrganization' : IDL.Func([IDL.Principal], [Organization], ['query']),
  'getSystemUserRecordsByIntegration' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SystemUserRecord)],
      ['query'],
    ),
  'getTimesheetRecord' : IDL.Func(
      [IDL.Principal],
      [TimesheetRecord],
      ['query'],
    ),
  'getUserMapping' : IDL.Func([IDL.Principal], [UserMapping], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateDashboard' : IDL.Func([IDL.Nat, IDL.Text, IDL.Vec(Widget)], [], []),
  'updateIntegration' : IDL.Func([IDL.Principal, Integration], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Alert = IDL.Record({
    'id' : IDL.Nat,
    'user' : IDL.Principal,
    'acknowledged' : IDL.Bool,
    'message' : IDL.Text,
  });
  const OrganizationType = IDL.Variant({
    'internalTA' : IDL.Null,
    'staffing' : IDL.Null,
  });
  const IntegrationType = IDL.Variant({
    'loxo' : IDL.Null,
    'timesheets' : IDL.Null,
    'aircall' : IDL.Null,
  });
  const SystemUserRecord = IDL.Record({
    'name' : IDL.Text,
    'integrationId' : IDL.Text,
    'email' : IDL.Text,
    'integrationType' : IntegrationType,
    'organization' : IDL.Principal,
  });
  const Time = IDL.Int;
  const TimesheetRecord = IDL.Record({
    'hours' : IDL.Float64,
    'userId' : IDL.Text,
    'date' : Time,
    'billable' : IDL.Bool,
    'organization' : IDL.Principal,
  });
  const UserMapping = IDL.Record({
    'timesheetUserId' : IDL.Opt(IDL.Text),
    'canisterUser' : IDL.Principal,
    'aircallUserId' : IDL.Opt(IDL.Text),
    'loxoUserId' : IDL.Opt(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const WidgetType = IDL.Variant({
    'table' : IDL.Null,
    'trendChart' : IDL.Null,
    'kpiCard' : IDL.Null,
  });
  const Widget = IDL.Record({
    'id' : IDL.Nat,
    'widgetType' : WidgetType,
    'config' : IDL.Text,
  });
  const Dashboard = IDL.Record({
    'id' : IDL.Nat,
    'widgets' : IDL.Vec(Widget),
    'owner' : IDL.Principal,
    'name' : IDL.Text,
  });
  const Integration = IDL.Record({
    'id' : IntegrationType,
    'apiKey' : IDL.Opt(IDL.Text),
    'connected' : IDL.Bool,
  });
  const Organization = IDL.Record({
    'principal' : IDL.Principal,
    'integrations' : IDL.Vec(Integration),
    'orgType' : OrganizationType,
    'name' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'organizationId' : IDL.Opt(IDL.Principal),
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acknowledgeAlert' : IDL.Func([IDL.Principal], [], []),
    'addAlert' : IDL.Func([Alert], [], []),
    'addOrganization' : IDL.Func([IDL.Text, OrganizationType], [], []),
    'addSystemUserRecord' : IDL.Func([SystemUserRecord], [], []),
    'addTimesheetRecord' : IDL.Func([TimesheetRecord], [], []),
    'addUserMapping' : IDL.Func([UserMapping], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createDashboard' : IDL.Func([IDL.Text, IDL.Vec(Widget)], [IDL.Nat], []),
    'getAlert' : IDL.Func([IDL.Principal], [Alert], ['query']),
    'getAllAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
    'getAllDashboards' : IDL.Func([], [IDL.Vec(Dashboard)], ['query']),
    'getAllOrganizations' : IDL.Func([], [IDL.Vec(Organization)], ['query']),
    'getAllTimesheetRecords' : IDL.Func(
        [],
        [IDL.Vec(TimesheetRecord)],
        ['query'],
      ),
    'getAllUserMappings' : IDL.Func([], [IDL.Vec(UserMapping)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboard' : IDL.Func([IDL.Nat], [Dashboard], ['query']),
    'getOrganization' : IDL.Func([IDL.Principal], [Organization], ['query']),
    'getSystemUserRecordsByIntegration' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SystemUserRecord)],
        ['query'],
      ),
    'getTimesheetRecord' : IDL.Func(
        [IDL.Principal],
        [TimesheetRecord],
        ['query'],
      ),
    'getUserMapping' : IDL.Func([IDL.Principal], [UserMapping], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateDashboard' : IDL.Func([IDL.Nat, IDL.Text, IDL.Vec(Widget)], [], []),
    'updateIntegration' : IDL.Func([IDL.Principal, Integration], [], []),
  });
};

export const init = ({ IDL }) => { return []; };