/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Organization {
    principal: Principal;
    integrations: Array<Integration>;
    orgType: OrganizationType;
    name: string;
}
export type Time = bigint;
export interface Widget {
    id: bigint;
    widgetType: WidgetType;
    config: string;
}
export interface SystemUserRecord {
    name: string;
    integrationId: string;
    email: string;
    integrationType: IntegrationType;
    organization: Principal;
}
export interface UserMapping {
    timesheetUserId?: string;
    canisterUser: Principal;
    aircallUserId?: string;
    loxoUserId?: string;
}
export interface Integration {
    id: IntegrationType;
    apiKey?: string;
    connected: boolean;
}
export interface Dashboard {
    id: bigint;
    widgets: Array<Widget>;
    owner: Principal;
    name: string;
}
export interface Alert {
    id: bigint;
    user: Principal;
    acknowledged: boolean;
    message: string;
}
export interface TimesheetRecord {
    hours: number;
    userId: string;
    date: Time;
    billable: boolean;
    organization: Principal;
}
export interface UserProfile {
    organizationId?: Principal;
    name: string;
    email?: string;
}
export enum IntegrationType {
    loxo = "loxo",
    timesheets = "timesheets",
    aircall = "aircall"
}
export enum OrganizationType {
    internalTA = "internalTA",
    staffing = "staffing"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum WidgetType {
    table = "table",
    trendChart = "trendChart",
    kpiCard = "kpiCard"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    acknowledgeAlert(alertId: Principal): Promise<void>;
    addAlert(alert: Alert): Promise<void>;
    addOrganization(name: string, orgType: OrganizationType): Promise<void>;
    addSystemUserRecord(record: SystemUserRecord): Promise<void>;
    addTimesheetRecord(record: TimesheetRecord): Promise<void>;
    addUserMapping(mapping: UserMapping): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createDashboard(name: string, widgets: Array<Widget>): Promise<bigint>;
    getAlert(id: Principal): Promise<Alert>;
    getAllAlerts(): Promise<Array<Alert>>;
    getAllDashboards(): Promise<Array<Dashboard>>;
    getAllOrganizations(): Promise<Array<Organization>>;
    getAllTimesheetRecords(): Promise<Array<TimesheetRecord>>;
    getAllUserMappings(): Promise<Array<UserMapping>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboard(dashboardId: bigint): Promise<Dashboard>;
    getOrganization(id: Principal): Promise<Organization>;
    getSystemUserRecordsByIntegration(integrationId: string): Promise<Array<SystemUserRecord>>;
    getTimesheetRecord(id: Principal): Promise<TimesheetRecord>;
    getUserMapping(id: Principal): Promise<UserMapping>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateDashboard(dashboardId: bigint, name: string, widgets: Array<Widget>): Promise<void>;
    updateIntegration(orgId: Principal, integration: Integration): Promise<void>;
}
import type { Dashboard as _Dashboard, Integration as _Integration, IntegrationType as _IntegrationType, Organization as _Organization, OrganizationType as _OrganizationType, SystemUserRecord as _SystemUserRecord, UserMapping as _UserMapping, UserProfile as _UserProfile, UserRole as _UserRole, Widget as _Widget, WidgetType as _WidgetType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async acknowledgeAlert(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acknowledgeAlert(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acknowledgeAlert(arg0);
            return result;
        }
    }
    async addAlert(arg0: Alert): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAlert(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAlert(arg0);
            return result;
        }
    }
    async addOrganization(arg0: string, arg1: OrganizationType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrganization(arg0, to_candid_OrganizationType_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrganization(arg0, to_candid_OrganizationType_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addSystemUserRecord(arg0: SystemUserRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSystemUserRecord(to_candid_SystemUserRecord_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSystemUserRecord(to_candid_SystemUserRecord_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addTimesheetRecord(arg0: TimesheetRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTimesheetRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTimesheetRecord(arg0);
            return result;
        }
    }
    async addUserMapping(arg0: UserMapping): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addUserMapping(to_candid_UserMapping_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addUserMapping(to_candid_UserMapping_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createDashboard(arg0: string, arg1: Array<Widget>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createDashboard(arg0, to_candid_vec_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDashboard(arg0, to_candid_vec_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAlert(arg0: Principal): Promise<Alert> {
        if (this.processError) {
            try {
                const result = await this.actor.getAlert(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAlert(arg0);
            return result;
        }
    }
    async getAllAlerts(): Promise<Array<Alert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAlerts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAlerts();
            return result;
        }
    }
    async getAllDashboards(): Promise<Array<Dashboard>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDashboards();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDashboards();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllOrganizations(): Promise<Array<Organization>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrganizations();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrganizations();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTimesheetRecords(): Promise<Array<TimesheetRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTimesheetRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTimesheetRecords();
            return result;
        }
    }
    async getAllUserMappings(): Promise<Array<UserMapping>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserMappings();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserMappings();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboard(arg0: bigint): Promise<Dashboard> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboard(arg0);
                return from_candid_Dashboard_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboard(arg0);
            return from_candid_Dashboard_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrganization(arg0: Principal): Promise<Organization> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrganization(arg0);
                return from_candid_Organization_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrganization(arg0);
            return from_candid_Organization_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSystemUserRecordsByIntegration(arg0: string): Promise<Array<SystemUserRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSystemUserRecordsByIntegration(arg0);
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSystemUserRecordsByIntegration(arg0);
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTimesheetRecord(arg0: Principal): Promise<TimesheetRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.getTimesheetRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTimesheetRecord(arg0);
            return result;
        }
    }
    async getUserMapping(arg0: Principal): Promise<UserMapping> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserMapping(arg0);
                return from_candid_UserMapping_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserMapping(arg0);
            return from_candid_UserMapping_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n47(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n47(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateDashboard(arg0: bigint, arg1: string, arg2: Array<Widget>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDashboard(arg0, arg1, to_candid_vec_n11(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDashboard(arg0, arg1, to_candid_vec_n11(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateIntegration(arg0: Principal, arg1: Integration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateIntegration(arg0, to_candid_Integration_n49(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateIntegration(arg0, to_candid_Integration_n49(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Dashboard_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Dashboard): Dashboard {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_IntegrationType_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IntegrationType): IntegrationType {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Integration_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Integration): Integration {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_OrganizationType_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrganizationType): OrganizationType {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Organization_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Organization): Organization {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_SystemUserRecord_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SystemUserRecord): SystemUserRecord {
    return from_candid_record_n46(_uploadFile, _downloadFile, value);
}
function from_candid_UserMapping_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserMapping): UserMapping {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid_WidgetType_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WidgetType): WidgetType {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Widget_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Widget): Widget {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n39(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    widgets: Array<_Widget>;
    owner: Principal;
    name: string;
}): {
    id: bigint;
    widgets: Array<Widget>;
    owner: Principal;
    name: string;
} {
    return {
        id: value.id,
        widgets: from_candid_vec_n19(_uploadFile, _downloadFile, value.widgets),
        owner: value.owner,
        name: value.name
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    widgetType: _WidgetType;
    config: string;
}): {
    id: bigint;
    widgetType: WidgetType;
    config: string;
} {
    return {
        id: value.id,
        widgetType: from_candid_WidgetType_n22(_uploadFile, _downloadFile, value.widgetType),
        config: value.config
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    integrations: Array<_Integration>;
    orgType: _OrganizationType;
    name: string;
}): {
    principal: Principal;
    integrations: Array<Integration>;
    orgType: OrganizationType;
    name: string;
} {
    return {
        principal: value.principal,
        integrations: from_candid_vec_n27(_uploadFile, _downloadFile, value.integrations),
        orgType: from_candid_OrganizationType_n33(_uploadFile, _downloadFile, value.orgType),
        name: value.name
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _IntegrationType;
    apiKey: [] | [string];
    connected: boolean;
}): {
    id: IntegrationType;
    apiKey?: string;
    connected: boolean;
} {
    return {
        id: from_candid_IntegrationType_n30(_uploadFile, _downloadFile, value.id),
        apiKey: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.apiKey)),
        connected: value.connected
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    timesheetUserId: [] | [string];
    canisterUser: Principal;
    aircallUserId: [] | [string];
    loxoUserId: [] | [string];
}): {
    timesheetUserId?: string;
    canisterUser: Principal;
    aircallUserId?: string;
    loxoUserId?: string;
} {
    return {
        timesheetUserId: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.timesheetUserId)),
        canisterUser: value.canisterUser,
        aircallUserId: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.aircallUserId)),
        loxoUserId: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.loxoUserId))
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    organizationId: [] | [Principal];
    name: string;
    email: [] | [string];
}): {
    organizationId?: Principal;
    name: string;
    email?: string;
} {
    return {
        organizationId: record_opt_to_undefined(from_candid_opt_n41(_uploadFile, _downloadFile, value.organizationId)),
        name: value.name,
        email: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.email))
    };
}
function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    integrationId: string;
    email: string;
    integrationType: _IntegrationType;
    organization: Principal;
}): {
    name: string;
    integrationId: string;
    email: string;
    integrationType: IntegrationType;
    organization: Principal;
} {
    return {
        name: value.name,
        integrationId: value.integrationId,
        email: value.email,
        integrationType: from_candid_IntegrationType_n30(_uploadFile, _downloadFile, value.integrationType),
        organization: value.organization
    };
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    table: null;
} | {
    trendChart: null;
} | {
    kpiCard: null;
}): WidgetType {
    return "table" in value ? WidgetType.table : "trendChart" in value ? WidgetType.trendChart : "kpiCard" in value ? WidgetType.kpiCard : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    loxo: null;
} | {
    timesheets: null;
} | {
    aircall: null;
}): IntegrationType {
    return "loxo" in value ? IntegrationType.loxo : "timesheets" in value ? IntegrationType.timesheets : "aircall" in value ? IntegrationType.aircall : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    internalTA: null;
} | {
    staffing: null;
}): OrganizationType {
    return "internalTA" in value ? OrganizationType.internalTA : "staffing" in value ? OrganizationType.staffing : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Dashboard>): Array<Dashboard> {
    return value.map((x)=>from_candid_Dashboard_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Widget>): Array<Widget> {
    return value.map((x)=>from_candid_Widget_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Organization>): Array<Organization> {
    return value.map((x)=>from_candid_Organization_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Integration>): Array<Integration> {
    return value.map((x)=>from_candid_Integration_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserMapping>): Array<UserMapping> {
    return value.map((x)=>from_candid_UserMapping_n36(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SystemUserRecord>): Array<SystemUserRecord> {
    return value.map((x)=>from_candid_SystemUserRecord_n45(_uploadFile, _downloadFile, x));
}
function to_candid_IntegrationType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IntegrationType): _IntegrationType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_Integration_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Integration): _Integration {
    return to_candid_record_n50(_uploadFile, _downloadFile, value);
}
function to_candid_OrganizationType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrganizationType): _OrganizationType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_SystemUserRecord_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SystemUserRecord): _SystemUserRecord {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserMapping_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserMapping): _UserMapping {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n48(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_WidgetType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WidgetType): _WidgetType {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_Widget_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Widget): _Widget {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    widgetType: WidgetType;
    config: string;
}): {
    id: bigint;
    widgetType: _WidgetType;
    config: string;
} {
    return {
        id: value.id,
        widgetType: to_candid_WidgetType_n14(_uploadFile, _downloadFile, value.widgetType),
        config: value.config
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    integrationId: string;
    email: string;
    integrationType: IntegrationType;
    organization: Principal;
}): {
    name: string;
    integrationId: string;
    email: string;
    integrationType: _IntegrationType;
    organization: Principal;
} {
    return {
        name: value.name,
        integrationId: value.integrationId,
        email: value.email,
        integrationType: to_candid_IntegrationType_n5(_uploadFile, _downloadFile, value.integrationType),
        organization: value.organization
    };
}
function to_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    organizationId?: Principal;
    name: string;
    email?: string;
}): {
    organizationId: [] | [Principal];
    name: string;
    email: [] | [string];
} {
    return {
        organizationId: value.organizationId ? candid_some(value.organizationId) : candid_none(),
        name: value.name,
        email: value.email ? candid_some(value.email) : candid_none()
    };
}
function to_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: IntegrationType;
    apiKey?: string;
    connected: boolean;
}): {
    id: _IntegrationType;
    apiKey: [] | [string];
    connected: boolean;
} {
    return {
        id: to_candid_IntegrationType_n5(_uploadFile, _downloadFile, value.id),
        apiKey: value.apiKey ? candid_some(value.apiKey) : candid_none(),
        connected: value.connected
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    timesheetUserId?: string;
    canisterUser: Principal;
    aircallUserId?: string;
    loxoUserId?: string;
}): {
    timesheetUserId: [] | [string];
    canisterUser: Principal;
    aircallUserId: [] | [string];
    loxoUserId: [] | [string];
} {
    return {
        timesheetUserId: value.timesheetUserId ? candid_some(value.timesheetUserId) : candid_none(),
        canisterUser: value.canisterUser,
        aircallUserId: value.aircallUserId ? candid_some(value.aircallUserId) : candid_none(),
        loxoUserId: value.loxoUserId ? candid_some(value.loxoUserId) : candid_none()
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WidgetType): {
    table: null;
} | {
    trendChart: null;
} | {
    kpiCard: null;
} {
    return value == WidgetType.table ? {
        table: null
    } : value == WidgetType.trendChart ? {
        trendChart: null
    } : value == WidgetType.kpiCard ? {
        kpiCard: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrganizationType): {
    internalTA: null;
} | {
    staffing: null;
} {
    return value == OrganizationType.internalTA ? {
        internalTA: null
    } : value == OrganizationType.staffing ? {
        staffing: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IntegrationType): {
    loxo: null;
} | {
    timesheets: null;
} | {
    aircall: null;
} {
    return value == IntegrationType.loxo ? {
        loxo: null
    } : value == IntegrationType.timesheets ? {
        timesheets: null
    } : value == IntegrationType.aircall ? {
        aircall: null
    } : value;
}
function to_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Widget>): Array<_Widget> {
    return value.map((x)=>to_candid_Widget_n12(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
